
title = "forge-tech"
baseURL = "https://forge-tech.dev"
homeSubtitle = "Wow, such subtitle"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "hermit-v2"
enableRobotsTXT = false
#publishDir = "../public"

languageCode = "en-us"
[languages]
  [languages.en]
    title = 'Forge-Tech'
    [languages.en.params]
      homeSubtitle = "We don’t just build technology — we forge..."
    languageCode = 'en-us'
    weight = 1
  [languages.de]
    title = 'Forge-Tech'
    [languages.de.params]
      homeSubtitle = "Wir entwickeln nicht nur Technologien – wir schmieden …"
      languageCode = 'de'
    weight = 2
  [languages.hr]
    title = 'Forge-Tech'
    [languages.hr.params]
      homeSubtitle = "Mi ne gradimo samo tehnologiju - mi kujemo..."
      languageCode = 'hr'
    weight = 3
 


pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10
enableEmoji = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]


[params.author]
  name = "Adam Miranda-Artizada"

[taxonomies]
  tag = "tags"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "Home of Forge-tech.dev"
  images = ["./images/Forge-Tech - No Background"]
  footerHideThemeName = true
  # bgImg = ""
  # gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = false
  # readTimeSeparator = ""
  # legacyLayout = false
  shareSocial = true
  # tagSymbol = "#"
  # categorySymbol = "⊲"
  pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  listLayout = ["description","tags","categories","legacy"]
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]
  # noIndex = false
  # denyRobots = "noindex, nofollow, noarchive"
  # allowRobots = "index, follow"
  siteNoIndex = true
  # noIndexPages = ["404 Page not found"]
  usesAnimation = true

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/f0rg3t3ch"

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://linkedin.com/aartizada"

  [[params.socialLinks]]
    name = "email"
    url = "mailto:info@forge-tech.dev"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20

[caches]
  [caches.images]
    dir = ':cacheDir/images'